"""Write the analyzer payload for the static lookup page."""

from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

from .universe import ACCESS_META, CURATED_AS_OF, SECTORS

ROOT = Path(__file__).resolve().parent.parent
ARTIFACTS = ROOT / "data" / "artifacts"
SITE = ROOT / "site"
ARTIFACTS.mkdir(parents=True, exist_ok=True)


def _clean(o):
    if isinstance(o, dict):
        return {str(k): _clean(v) for k, v in o.items()}
    if isinstance(o, (list, tuple)):
        return [_clean(v) for v in o]
    if isinstance(o, np.integer):
        return int(o)
    if isinstance(o, (np.floating, float)):
        f = float(o)
        return None if (np.isnan(f) or np.isinf(f)) else round(f, 6)
    if isinstance(o, pd.Timestamp):
        return str(o.date())
    if isinstance(o, np.ndarray):
        return _clean(o.tolist())
    return o


def _monthly(s: pd.Series) -> list[dict]:
    if s.empty:
        return []
    m = s.resample("ME").last().dropna()
    return [{"d": str(pd.Timestamp(i).date())[:7], "v": round(float(v), 3)} for i, v in m.items()]


def build_payload(companies: list[dict], prices: pd.DataFrame, lineage: list) -> dict:
    series = {}
    for c in companies:
        t = c["ticker"]
        if t in prices.columns:
            series[t] = _monthly(prices[t].dropna())

    return {
        "meta": {
            "title": "China Company Analyzer",
            "subtitle": "Look up any major Chinese listed company and see what it does, "
                        "how it is performing, and how exposed it is to the United States.",
            "generated_at": datetime.now().isoformat(timespec="seconds"),
            "curated_as_of": CURATED_AS_OF,
            "n_companies": len(companies),
            "sectors": SECTORS,
            "access_meta": ACCESS_META,
        },
        "companies": _clean(companies),
        "series": _clean(series),
        "lineage": _clean(lineage),
        "limitations": [
            "US-business information (sales channel, regulatory status, tariff exposure) is "
            f"hand-researched as of {CURATED_AS_OF}. It does not update nightly, and each "
            "entry carries a confidence level. Financials and prices do update.",
            "US revenue share is shown only where a company discloses a geographic split or "
            "it is otherwise well documented. A blank means not disclosed, not zero.",
            "The US-market beta measures how a stock moves with the S&P 500. It is a "
            "sentiment linkage, not a measure of revenue from American customers — NIO "
            "trades with US risk appetite while selling no cars there.",
            "Weekly returns are used for beta because Hong Kong closes before New York opens; "
            "daily co-movement would understate the relationship for mechanical reasons.",
            "Mainland A-share-only companies are absent — they are geo-blocked from this "
            "network. That excludes Cambricon, Hygon, NAURA, AMEC and iFlytek.",
            "Financial figures come from Yahoo Finance and are converted to USD at current "
            "spot. Chinese disclosure quality is uneven and restated figures are common.",
            "Nothing here is a forecast or investment advice.",
        ],
    }


def write(payload: dict) -> None:
    data = _clean(payload)
    (ARTIFACTS / "analyzer.json").write_text(json.dumps(data, indent=2, ensure_ascii=False))
    (SITE / "data.js").write_text(
        "// Generated by analyzer.export — do not edit by hand.\n"
        "window.ANALYZER = " + json.dumps(data, ensure_ascii=False, separators=(",", ":")) + ";\n")
